name: Bandit Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
# 1. Checkout the code using actions/checkout
      - uses: actions/checkout@v4
# 2. Run bandit using tj-actions bandit
      - name: Run bandit
        uses: tj-actions/bandit@v5.1


  