
name: IAC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
    chekov:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkov GitHub Action
              uses: bridgecrewio/checkov-action@v12
              with:
                directory: IAC/
                # This will add CLI output to the console 
                output_format: cli
                output_file_path: console
    