
name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      
    # 1. Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4
    # 2. Build the docker image localy 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the docker image
        run: docker build -t "my-app:latest" .
    # 3. Run the docker Container
      - name: Run the docker container
        run: docker run "my-app"
    # 4. Run OWASP ZAP on the running webserver
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://127.0.0.1/'


