name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      # 2. Instal docker buildx  docker/setup-buildx-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 3. Build the docker image
      - name: Build and push
        uses: docker build -t 'my-image:latest'


      # 4. Scan with trivy the built image
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'my-image:latest'
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

